; Generated by AXY Compiler 2026-08-10 04:36

; AXY Test Program - Tests all compiler features
; Run: ./axy test-program.axy test-program.asm

; ============================================
; Program start (via an implicit constant chain)
; ============================================

start_addr = &1900
variables = &100

org_addr = start_addr
	org org_addr; emitted as 'org org_addr'; BeebAsm resolves the chain

; ============================================
; Variable declarations
; ============================================


lives = &100
score = &101
counter = &102
temp = &103

; ============================================
; Constants
; ============================================
; Every constant is emitted as a BeebAsm symbol and referenced by name.

limit = 100; number constant
maximum = limit; constant chain - referenced as #maximum, not #limit
lives_limit = 5; implicit number constant (no 'const' keyword)
max_value = 99
target = 10; explicit 'const' directive still works
zero = 0
space = ' '; character constant (ASCII value)
welcomemessage = "Hello and welcome to our resturant"; unused string constant in this source file but defined in beebasm for others to use

; ============================================
; Test 1: Basic assignment (number constants)
; ============================================

.start
	lda #lives_limit; LDA #lives_limit / STA lives
	sta lives
	lda #zero; LDA #zero / STA score
	sta score
	lda #target; LDA #target / STA counter
	sta counter
	lda #max_value; LDA #max_value / STA temp
	sta temp

; ============================================
; Test 2: Constants referenced by name
; ============================================

	lda #maximum; chain by name -> LDA #maximum
	ldx #space; character    -> LDX #space
	lda #maximum; chain by name -> LDA #maximum / STA temp
	sta temp

; ============================================
; Test 3: Register operations
; ============================================

	lda #42; LDA #42
	ldx lives; LDX lives
	stx lives; STX lives
	ldy counter; LDY counter
	sty counter; STY counter

; ============================================
; Test 4: Register transfers
; ============================================

	txa; TXA
	tax; TAX
	tya; TYA
	tay; TAY

; ============================================
; Test 5: Increment/Decrement
; ============================================

	inx; INX
	dex; DEX
	iny; INY
	dey; DEY

	inc lives; INC lives
	dec score; DEC score
	inc counter; INC counter

; ============================================
; Test 6: Labels and unconditional jumps
; ============================================

	inc temp
	jmp start

; ============================================
; Test 7: If statements
; ============================================

.check_lives
	lda lives
	cmp #lives_limit
{
	bne endif1
	lda #100
	sta score
.endif1
}

	lda lives
	cmp #5
{
	beq endif2
	lda #0
	sta score
.endif2
}

	cmp #space; CMP #space
{
	bne endif3
	lda #1
	sta score
.endif3
}

	lda #maximum; const on the left: LDA #maximum / CMP #limit
	cmp #limit
{
	bne endif4
	lda #0
	sta score
.endif4
}

; ============================================
; Test 8: While loop
; ============================================

	lda #10
	sta counter
{
.while5
	lda counter
	cmp #0
	beq endwhile6
	inc score
	dec counter
	jmp while5
.endwhile6
}

; ============================================
; Test 9: Nested control flow
; ============================================

	lda #5
	sta counter
.outer
	lda counter
	cmp #0
{
	bne endif7
	jmp done
.endif7
}

	lda #3
	sta temp

.inner
	lda temp
	cmp #0
{
	bne endif8
	jmp next
.endif8
}

	inc score
	dec temp
	jmp inner

.next

	dec counter
	jmp outer

; ============================================
; Test 10: Assembler mode (asm / endasm)
; ============================================
; Raw BeebAsm passes through verbatim. AXY variables and constants are known
; inside an asm block, and a constant defined there is usable from AXY.


secret = &47            ; constant defined in raw asm

	ldx #0
.loop_a

	txa
	sta lives,X             ; AXY variable
	inx
	cpx #limit              ; AXY constant
	bne loop_a

	lda #&A5                ; BeebAsm-only notation, never parsed by AXY
	sta temp


	lda #secret; LDA #secret - asm-defined constant

; ============================================
; Final - all tests passed
; ============================================

.done

	lda #42; Success marker
