; Generated by AXY Compiler 2026-08-10 02:37
start_addr = &1900
variables = &100
org_addr = start_addr
lives = &100
score = &101
counter = &102
temp = &103
limit = 100
maximum = limit
lives_limit = 5
max_value = 99
target = 10
zero = 0
space = 'A'
welcomemessage = "Hello and welcome to our resturant"

	org org_addr

.start
	lda #lives_limit
	sta lives
	lda #zero
	sta score
	lda #target
	sta counter
	lda #max_value
	sta temp
	lda #maximum
	ldx #space
	lda #maximum
	sta temp
	lda #42
	ldx lives
	stx lives
	ldy counter
	sty counter
	txa
	tax
	tya
	tay
	inx
	dex
	iny
	dey
	inc lives
	dec score
	inc counter
	inc temp
	lda temp
	cmp #10
{
	bne endif1
	jmp done
.endif1
}
	jmp start
.check_lives
	lda lives
	cmp #lives_limit
{
	bne endif2
	lda #100
	sta score
.endif2
}
	lda lives
	cmp #5
{
	beq endif3
	lda #0
	sta score
.endif3
}
	cmp #space
{
	bne endif4
	lda #1
	sta score
.endif4
}
	lda #maximum
	cmp #limit
{
	bne endif5
	lda #0
	sta score
.endif5
}
	lda #10
	sta counter
{
.while6
	lda counter
	cmp #0
	beq endwhile7
	inc score
	dec counter
	jmp while6
.endwhile7
}
	lda #5
	sta counter
.outer
	lda counter
	cmp #0
{
	bne endif8
	jmp done
.endif8
}
	lda #3
	sta temp
.inner
	lda temp
	cmp #0
{
	bne endif9
	jmp next
.endif9
}
	inc score
	dec temp
	jmp inner
.next
	dec counter
	jmp outer
.done
	lda #42
